package ifd

import (
	"github.com/vault-thirteen/TIFFermodels/Tag"
	"github.com/vault-thirteen/TIFFermodels/Type"
)

const ErrTypeIsNotValid = "type is not valid: %v"

// validTypesPerTag stores a map of valid data item models for each tag.
// If there are no matches for a tag, then there are no limitations for it.
var validTypesPerTag = map[tag.Tag][]t.Type{
	tag.NewSubfileType:            {t.Long},
	tag.SubfileType:               {t.Short},
	tag.ImageWidth:                {t.Short, t.Long},
	tag.ImageLength:               {t.Short, t.Long},
	tag.BitsPerSample:             {t.Short},
	tag.Compression:               {t.Short},
	tag.PhotometricInterpretation: {t.Short},
	tag.Threshholding:             {t.Short},
	tag.CellWidth:                 {t.Short},
	tag.CellLength:                {t.Short},
	tag.FillOrder:                 {t.Short},
	tag.DocumentName:              {t.ASCII},
	tag.ImageDescription:          {t.ASCII},
	tag.Make:                      {t.ASCII},
	tag.Model:                     {t.ASCII},
	tag.StripOffsets:              {t.Short, t.Long},
	tag.Orientation:               {t.Short},
	tag.SamplesPerPixel:           {t.Short},
	tag.RowsPerStrip:              {t.Short, t.Long},
	tag.StripByteCounts:           {t.Short, t.Long},
	tag.MinSampleValue:            {t.Short},
	tag.MaxSampleValue:            {t.Short},
	tag.XResolution:               {t.Rational},
	tag.YResolution:               {t.Rational},
	tag.PlanarConfiguration:       {t.Short},
	tag.PageName:                  {t.ASCII},
	tag.XPosition:                 {t.Rational},
	tag.YPosition:                 {t.Rational},
	tag.FreeOffsets:               {t.Long},
	tag.FreeByteCounts:            {t.Long},
	tag.GrayResponseUnit:          {t.Short},
	tag.GrayResponseCurve:         {t.Short},
	tag.T4Options:                 {t.Long},
	tag.T6Options:                 {t.Long},
	tag.ResolutionUnit:            {t.Short},
	tag.PageNumber:                {t.Short},
	tag.TransferFunction:          {t.Short},
	tag.Software:                  {t.ASCII},
	tag.DateTime:                  {t.ASCII},
	tag.Artist:                    {t.ASCII},
	tag.HostComputer:              {t.ASCII},
	tag.Predictor:                 {t.Short},
	tag.WhitePoint:                {t.Rational},
	tag.PrimaryChromaticities:     {t.Rational},
	tag.ColorMap:                  {t.Short},
	tag.HalftoneHints:             {t.Short},
	tag.TileWidth:                 {t.Short, t.Long},
	tag.TileLength:                {t.Short, t.Long},
	tag.TileOffsets:               {t.Long},
	tag.TileByteCounts:            {t.Short, t.Long},
	tag.BadFaxLines:               {t.Short, t.Long},
	tag.CleanFaxData:              {t.Short},
	tag.ConsecutiveBadFaxLines:    {t.Short, t.Long},
	tag.SubIFDs:                   {t.Long},
	tag.InkSet:                    {t.Short},
	tag.InkNames:                  {t.ASCII},
	tag.NumberOfInks:              {t.Short},
	tag.DotRange:                  {t.Byte, t.Short},
	tag.TargetPrinter:             {t.ASCII},
	tag.ExtraSamples:              {t.Short},
	tag.SampleFormat:              {t.Short},

	// https://www.awaresystems.be/imaging/tiff/tifftags/sminsamplevalue.html
	tag.SMinSampleValue: {t.Byte, t.Short, t.Long, t.SRational, t.Double},

	// https://www.awaresystems.be/imaging/tiff/tifftags/smaxsamplevalue.html
	tag.SMaxSampleValue: {t.Byte, t.Short, t.Long, t.SRational, t.Double},

	tag.TransferRange:               {t.Short},
	tag.ClipPath:                    {t.Byte},
	tag.XClipPathUnits:              {t.Long},
	tag.YClipPathUnits:              {t.Long},
	tag.Indexed:                     {t.Short},
	tag.JPEGTables:                  {t.Undefined},
	tag.OPIProxy:                    {t.Short},
	tag.GlobalParametersIFD:         {t.Long},
	tag.ProfileType:                 {t.Long},
	tag.FaxProfile:                  {t.Byte},
	tag.CodingMethods:               {t.Long},
	tag.VersionYear:                 {t.Byte},
	tag.ModeNumber:                  {t.Byte},
	tag.Decode:                      {t.SRational},
	tag.DefaultImageColor:           {t.Short},
	tag.JPEGProc:                    {t.Short},
	tag.JPEGInterchangeFormat:       {t.Long},
	tag.JPEGInterchangeFormatLength: {t.Long},
	tag.JPEGRestartInterval:         {t.Short},
	tag.JPEGLosslessPredictors:      {t.Short},
	tag.JPEGPointTransforms:         {t.Short},
	tag.JPEGQTables:                 {t.Long},
	tag.JPEGDCTables:                {t.Long},
	tag.JPEGACTables:                {t.Long},
	tag.YCbCrCoefficients:           {t.Rational},
	tag.YCbCrSubSampling:            {t.Short},
	tag.YCbCrPositioning:            {t.Short},
	tag.ReferenceBlackWhite:         {t.Rational},
	tag.StripRowCounts:              {t.Long},
	tag.XMP:                         {t.Byte},

	// Private Tags.
	tag.ImageID:         {t.ASCII},
	tag.WangAnnotation:  {t.Byte},
	tag.Copyright:       {t.ASCII},
	tag.MDFile:          {t.Long},
	tag.MDScalePixel:    {t.Rational},
	tag.MDColorTable:    {t.Short},
	tag.MDLabName:       {t.ASCII},
	tag.MDSampleInfo:    {t.ASCII},
	tag.MDPrepDate:      {t.ASCII},
	tag.MDPrepTime:      {t.ASCII},
	tag.MDFileUnits:     {t.ASCII},
	tag.ModelPixelScale: {t.Double},

	//tag.IPTC: {t.Undefined, t.Byte}, // Official.
	tag.IPTC: {t.Undefined, t.Byte, t.Long}, // Shitty tools.

	tag.INGRPacketData:               {t.Short},
	tag.INGRFlagRegisters:            {t.Long},
	tag.IrasBTransformationMatrix:    {t.Double},
	tag.ModelTiepoint:                {t.Double},
	tag.ModelTransformation:          {t.Double},
	tag.Photoshop:                    {t.Byte},
	tag.ExifIFD:                      {t.Long},
	tag.ICCProfile:                   {t.Undefined},
	tag.ImageLayer:                   {t.Short, t.Long},
	tag.GeoKeyDirectory:              {t.Short},
	tag.GeoDoubleParams:              {t.Double},
	tag.GeoAsciiParams:               {t.ASCII},
	tag.GPSIFD:                       {t.Long},
	tag.HylaFAXFaxRecvParams:         {t.Long},
	tag.HylaFAXFaxSubAddress:         {t.ASCII},
	tag.HylaFAXFaxRecvTime:           {t.Long},
	tag.ImageSourceData:              {t.Undefined},
	tag.InteroperabilityIFD:          {t.Long},
	tag.GDAL_METADATA:                {t.ASCII},
	tag.GDAL_NODATA:                  {t.ASCII},
	tag.OceScanjobDescription:        {t.ASCII},
	tag.OceApplicationSelector:       {t.ASCII},
	tag.OceIdentificationNumber:      {t.ASCII},
	tag.OceImageLogicCharacteristics: {t.ASCII},
	tag.DNGVersion:                   {t.Byte},
	tag.DNGBackwardVersion:           {t.Byte},
	tag.UniqueCameraModel:            {t.ASCII},
	tag.LocalizedCameraModel:         {t.Byte, t.ASCII},
	tag.CFAPlaneColor:                {t.Byte},
	tag.CFALayout:                    {t.Short},
	tag.LinearizationTable:           {t.Short},
	tag.BlackLevelRepeatDim:          {t.Short},
	tag.BlackLevel:                   {t.Short, t.Long, t.Rational},
	tag.BlackLevelDeltaH:             {t.SRational},
	tag.BlackLevelDeltaV:             {t.SRational},
	tag.WhiteLevel:                   {t.Short, t.Long, t.Rational},
	tag.DefaultScale:                 {t.Rational},
	tag.DefaultCropOrigin:            {t.Short, t.Long, t.Rational},
	tag.DefaultCropSize:              {t.Short, t.Long, t.Rational},
	tag.ColorMatrix1:                 {t.SRational},
	tag.ColorMatrix2:                 {t.SRational},
	tag.CameraCalibration1:           {t.SRational},
	tag.CameraCalibration2:           {t.SRational},
	tag.ReductionMatrix1:             {t.SRational},
	tag.ReductionMatrix2:             {t.SRational},
	tag.AnalogBalance:                {t.Rational},
	tag.AsShotNeutral:                {t.Short, t.Rational},
	tag.AsShotWhiteXY:                {t.Rational},
	tag.BaselineExposure:             {t.SRational},
	tag.BaselineNoise:                {t.Rational},
	tag.BaselineSharpness:            {t.Rational},
	tag.BayerGreenSplit:              {t.Long},
	tag.LinearResponseLimit:          {t.Rational},
	tag.CameraSerialNumber:           {t.ASCII},
	tag.LensInfo:                     {t.Rational},
	tag.ChromaBlurRadius:             {t.Rational},
	tag.AntiAliasStrength:            {t.Rational},
	tag.ShadowScale:                  {t.Rational},
	tag.DNGPrivateData:               {t.Byte},
	tag.MakerNoteSafety:              {t.Short},
	tag.CalibrationIlluminant1:       {t.Short},
	tag.CalibrationIlluminant2:       {t.Short},
	tag.BestQualityScale:             {t.Rational},
	tag.RawDataUniqueID:              {t.Byte},
	tag.AliasLayerMetadata:           {t.ASCII},
	tag.OriginalRawFileName:          {t.Byte, t.ASCII},
	tag.OriginalRawFileData:          {t.Undefined},
	tag.ActiveArea:                   {t.Short, t.Long},
	tag.MaskedAreas:                  {t.Short, t.Long},
	tag.AsShotICCProfile:             {t.Undefined},
	tag.AsShotPreProfileMatrix:       {t.SRational},
	tag.CurrentICCProfile:            {t.Undefined},
	tag.CurrentPreProfileMatrix:      {t.SRational},
	tag.ColorimetricReference:        {t.Short},
	tag.TIFF_RSID:                    {t.ASCII},
	tag.GEO_METADATA:                 {t.Byte},
	tag.CameraCalibrationSignature:   {t.Byte, t.ASCII},
	tag.ProfileCalibrationSignature:  {t.Byte, t.ASCII},
	tag.ExtraCameraProfiles:          {t.Long},
	tag.AsShotProfileName:            {t.Byte, t.ASCII},
	tag.NoiseReductionApplied:        {t.Rational},
	tag.ProfileName:                  {t.Byte, t.ASCII},
	tag.ProfileHueSatMapDims:         {t.Long},
	tag.ProfileHueSatMapData1:        {t.Float},
	tag.ProfileHueSatMapData2:        {t.Float},
	tag.ProfileToneCurve:             {t.Float},
	tag.ProfileEmbedPolicy:           {t.Long},
	tag.ProfileCopyright:             {t.Byte, t.ASCII},
	tag.ForwardMatrix1:               {t.SRational},
	tag.ForwardMatrix2:               {t.SRational},
	tag.PreviewApplicationName:       {t.Byte, t.ASCII},
	tag.PreviewApplicationVersion:    {t.Byte, t.ASCII},
	tag.PreviewSettingsName:          {t.Byte, t.ASCII},
	tag.PreviewSettingsDigest:        {t.Byte},
	tag.PreviewColorSpace:            {t.Long},
	tag.PreviewDateTime:              {t.ASCII},
	tag.RawImageDigest:               {t.Byte},
	tag.OriginalRawFileDigest:        {t.Byte},
	tag.SubTileBlockSize:             {t.Short, t.Long},
	tag.RowInterleaveFactor:          {t.Short, t.Long},
	tag.ProfileLookTableDims:         {t.Long},
	tag.ProfileLookTableData:         {t.Float},
	tag.OpcodeList1:                  {t.Undefined},
	tag.OpcodeList2:                  {t.Undefined},
	tag.OpcodeList3:                  {t.Undefined},
	tag.NoiseProfile:                 {t.Double},
	tag.OriginalDefaultFinalSize:     {t.Short, t.Long},
	tag.OriginalBestQualityFinalSize: {t.Short, t.Long},
	tag.OriginalDefaultCropSize:      {t.Short, t.Long, t.Rational},
	tag.ProfileHueSatMapEncoding:     {t.Long},
	tag.ProfileLookTableEncoding:     {t.Long},
	tag.BaselineExposureOffset:       {t.Rational},
	tag.DefaultBlackRender:           {t.Long},
	tag.NewRawImageDigest:            {t.Byte},
	tag.RawToPreviewGain:             {t.Double},
	tag.DefaultUserCrop:              {t.Rational},
	tag.DepthFormat:                  {t.Short},
	tag.DepthNear:                    {t.Rational},
	tag.DepthFar:                     {t.Rational},
	tag.DepthUnits:                   {t.Short},
	tag.DepthMeasureType:             {t.Short},
	tag.EnhanceParams:                {t.ASCII},

	// EXIF Tags.
	tag.ExposureTime:        {t.Rational},
	tag.FNumber:             {t.Rational},
	tag.ExposureProgram:     {t.Short},
	tag.SpectralSensitivity: {t.ASCII},
	tag.ISOSpeedRatings:     {t.Short},
	tag.OECF:                {t.Undefined},

	// Some shitty tools use Byte type instead of the documented Undefined type:
	// https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/exif/exifversion.html
	//tag.ExifVersion: {t.Undefined}, // Official.
	tag.ExifVersion: {t.ASCII, t.Undefined}, // For shitty tools.

	tag.DateTimeOriginal:         {t.ASCII},
	tag.DateTimeDigitized:        {t.ASCII},
	tag.ComponentsConfiguration:  {t.Undefined},
	tag.CompressedBitsPerPixel:   {t.Rational},
	tag.ShutterSpeedValue:        {t.SRational},
	tag.ApertureValue:            {t.Rational},
	tag.BrightnessValue:          {t.SRational},
	tag.ExposureBiasValue:        {t.SRational},
	tag.MaxApertureValue:         {t.Rational},
	tag.SubjectDistance:          {t.Rational},
	tag.MeteringMode:             {t.Short},
	tag.LightSource:              {t.Short},
	tag.Flash:                    {t.Short},
	tag.FocalLength:              {t.Rational},
	tag.SubjectArea:              {t.Short},
	tag.MakerNote:                {t.Undefined},
	tag.UserComment:              {t.Undefined},
	tag.SubsecTime:               {t.ASCII},
	tag.SubsecTimeOriginal:       {t.ASCII},
	tag.SubsecTimeDigitized:      {t.ASCII},
	tag.FlashpixVersion:          {t.Undefined},
	tag.ColorSpace:               {t.Short},
	tag.PixelXDimension:          {t.Short, t.Long},
	tag.PixelYDimension:          {t.Short, t.Long},
	tag.RelatedSoundFile:         {t.ASCII},
	tag.FlashEnergy:              {t.Rational},
	tag.SpatialFrequencyResponse: {t.Undefined},
	tag.FocalPlaneXResolution:    {t.Rational},
	tag.FocalPlaneYResolution:    {t.Rational},
	tag.FocalPlaneResolutionUnit: {t.Short},
	tag.SubjectLocation:          {t.Short},
	tag.ExposureIndex:            {t.Rational},
	tag.SensingMethod:            {t.Short},
	tag.FileSource:               {t.Undefined},
	tag.SceneType:                {t.Undefined},
	tag.CFAPattern:               {t.Undefined},
	tag.CustomRendered:           {t.Short},
	tag.ExposureMode:             {t.Short},
	tag.WhiteBalance:             {t.Short},
	tag.DigitalZoomRatio:         {t.Rational},
	tag.FocalLengthIn35mmFilm:    {t.Short},
	tag.SceneCaptureType:         {t.Short},
	tag.GainControl:              {t.Short},
	tag.Contrast:                 {t.Short},
	tag.Saturation:               {t.Short},
	tag.Sharpness:                {t.Short},
	tag.DeviceSettingDescription: {t.Undefined},
	tag.SubjectDistanceRange:     {t.Short},
	tag.ImageUniqueID:            {t.ASCII},

	// GPS Tags.
	tag.GPSVersionID:        {t.Byte},
	tag.GPSLatitudeRef:      {t.ASCII},
	tag.GPSLatitude:         {t.Rational},
	tag.GPSLongitudeRef:     {t.ASCII},
	tag.GPSLongitude:        {t.Rational},
	tag.GPSAltitudeRef:      {t.Byte},
	tag.GPSAltitude:         {t.Rational},
	tag.GPSTimeStamp:        {t.Rational},
	tag.GPSSatellites:       {t.ASCII},
	tag.GPSStatus:           {t.ASCII},
	tag.GPSMeasureMode:      {t.ASCII},
	tag.GPSDOP:              {t.Rational},
	tag.GPSSpeedRef:         {t.ASCII},
	tag.GPSSpeed:            {t.Rational},
	tag.GPSTrackRef:         {t.ASCII},
	tag.GPSTrack:            {t.Rational},
	tag.GPSImgDirectionRef:  {t.ASCII},
	tag.GPSImgDirection:     {t.Rational},
	tag.GPSMapDatum:         {t.ASCII},
	tag.GPSDestLatitudeRef:  {t.ASCII},
	tag.GPSDestLatitude:     {t.Rational},
	tag.GPSDestLongitudeRef: {t.ASCII},
	tag.GPSDestLongitude:    {t.Rational},
	tag.GPSDestBearingRef:   {t.ASCII},
	tag.GPSDestBearing:      {t.Rational},
	tag.GPSDestDistanceRef:  {t.ASCII},
	tag.GPSDestDistance:     {t.Rational},
	tag.GPSProcessingMethod: {t.Undefined},
	tag.GPSAreaInformation:  {t.Undefined},
	tag.GPSDateStamp:        {t.ASCII},
	tag.GPSDifferential:     {t.Short},
}

func ValidTypesPerTag() map[tag.Tag][]t.Type {
	return validTypesPerTag
}

// hasValidType checks correctness of the DE's data item type by its tag.
func (de *DirectoryEntry) hasValidType() (isValid bool) {
	validTypes, ruleExists := validTypesPerTag[de.Tag]

	// Unknown tags are not checked, as stated in the TIFF 6.0 Specification.
	if !ruleExists {
		de.isTypeRegistered = false
		return true
	}

	de.isTypeRegistered = true
	for _, validType := range validTypes {
		if de.Type == validType {
			return true
		}
	}

	return false
}
